# Generated by Django 4.2 on 2024-02-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('link', models.URLField(default='https://www.goodreads.com/', max_length=255, verbose_name='Link')),
                ('author', models.CharField(max_length=255, verbose_name='Autor')),
                ('rating', models.CharField(max_length=255, verbose_name='Rating')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ('id',),
            },
        ),
    ]
